//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.ccdb.session.view.jaxws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

@XmlRootElement(name = "createCCInfo", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createCCInfo", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/")
public class CreateCCInfo {

    @XmlElement(name = "arg0", namespace = "")
    private com.ibm.websphere.svt.gs.ccdb.entities.CcInfo arg0;

    /**
     * 
     * @return
     *     returns CcInfo
     */
    public com.ibm.websphere.svt.gs.ccdb.entities.CcInfo getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(com.ibm.websphere.svt.gs.ccdb.entities.CcInfo arg0) {
        this.arg0 = arg0;
    }

}
