services: docker

jdk:
- openjdk17

git:
  submodules: false

before_install:
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD

# - sudo apt-get -y install maven

script:
#- jdk_switcher use openjdk17
#- jdk_switcher use openjdk17
#- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
#- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
#- export JAVA_HOME=$HOME/openjdk17
#- $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
- echo "JAVA_HOME=$JAVA_HOME"
- echo "TRAVIS_JDK_VERSION=$TRAVIS_JDK_VERSION"
- HYCSVT="$CONT_REGISTRY/hyc-wassvt-team-image-registry-docker-local"
- echo "$REG_USER" > /tmp/.user
- echo "$REG_PASSWORD" > /tmp/.token
- docker login $CONT_REGISTRY -u $(cat /tmp/.user) -p $(cat /tmp/.token)
- export DOCKER_BUILDKIT=1
#- export BUILDKIT_COLORS=run=123,20,245:error=yellow:cancel=blue:warning=white
- export BUILDKIT_PROGRESS=plain
- mvn -q clean package
- docker build -t garagesale-ee -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg OL=false  --build-arg FULL_IMAGE=true .
- tag=`git log --pretty=format:"%h" -1`
- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:$tag
- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:ee10jdk17
#- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:latest
#- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:ga
- docker push  $HYCSVT/garagesale/garagesale-ee:$tag
#- docker push  $HYCSVT/garagesale/garagesale-ee:latest
- docker push  $HYCSVT/garagesale/garagesale-ee:ee10jdk17
#- docker push  $HYCSVT/garagesale/garagesale-ee:ga
