services: docker

jdk:
- openjdk17

git:
  submodules: false

before_install:
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD

# - sudo apt-get -y install maven

script:
#- jdk_switcher use openjdk17
#- jdk_switcher use openjdk17
#- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
#- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
#- export JAVA_HOME=$HOME/openjdk17
#- $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
- mvn clean package
- docker build -t garagesale-ee -f Containerfile --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg OL=false  --build-arg FULL_IMAGE=true .
- tag=`git log --pretty=format:"%h" -1`
- docker tag garagesale-ee $CONT_REGISTRY/garagesale/garagesale-ee:$tag
- docker tag garagesale-ee $CONT_REGISTRY/garagesale/garagesale-ee:ee10jdk17tol
#- docker tag garagesale-ee $CONT_REGISTRY/garagesale/garagesale-ee:latest
#- docker tag garagesale-ee $CONT_REGISTRY/garagesale/garagesale-ee:ga
- docker push  $CONT_REGISTRY/garagesale/garagesale-ee:$tag
#- docker push  $CONT_REGISTRY/garagesale/garagesale-ee:latest
- docker push  $CONT_REGISTRY/garagesale/garagesale-ee:ee10jdk17tol
#- docker push  $CONT_REGISTRY/garagesale/garagesale-ee:ga
