services: docker

jdk:
- openjdk17

git:
  submodules: false

before_install:
- sudo apt -y install python3 python3-pip
- sudo pip3 install setuptools
- sudo pip3 install --upgrade pip
- sudo pip3 install --upgrade setuptools
- sudo pip3 install ansible

script:
#- jdk_switcher use openjdk17
#- jdk_switcher use openjdk17
#- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
#- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
#- export JAVA_HOME=$HOME/openjdk17
#- $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
- |
  git clone https://$GITHUB_TOKEN@github.ibm.com/was-svt/configs.git --branch main -q
  echo "$pw" > /tmp/.pw
  configs/bin/decryptme.sh /tmp/.pw
  # env vars from the configs repo CONT_REGISTRY HYCSVT and the user / token
  . /tmp/.registry
  docker login $CONT_REGISTRY -u $(cat /tmp/.user) -p $(cat /tmp/.token)

- echo "JAVA_HOME=$JAVA_HOME"
- echo "TRAVIS_JDK_VERSION=$TRAVIS_JDK_VERSION"
- export DOCKER_BUILDKIT=1
#- export BUILDKIT_COLORS=run=123,20,245:error=yellow:cancel=blue:warning=white
- export BUILDKIT_PROGRESS=plain
- mvn -q clean package
- docker build -t garagesale-ee -f Containerfile --secret id=token,src=/tmp/.token --secret id=user,src=/tmp/.user --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg OL=false  --build-arg FULL_IMAGE=true .
- tag=`git log --pretty=format:"%h" -1`
- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:$tag
- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:ee10jdk17
#- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:latest
#- docker tag garagesale-ee $HYCSVT/garagesale/garagesale-ee:ga
- docker push  $HYCSVT/garagesale/garagesale-ee:$tag
#- docker push  $HYCSVT/garagesale/garagesale-ee:latest
- docker push  $HYCSVT/garagesale/garagesale-ee:ee10jdk17
#- docker push  $HYCSVT/garagesale/garagesale-ee:ga
