FROM websphere-liberty:latest
#RUN installUtility install --acceptLicense logstashCollector-1.0

RUN installUtility install --acceptLicense defaultServer

COPY GarageSaleRuntimeUtil/target/wlp/usr/servers/garageSaleServer/apps/GarageSaleLibertyEAR.ear /config/apps/GarageSaleLibertyEAR.ear
COPY GarageSaleRuntimeUtil/publish/servers/server.db2.static.minikube.xml /config/server.xml
COPY GarageSaleRuntimeUtil/publish/files/jvm.options /config/jvm.options
COPY GarageSaleRuntimeUtil/publish/files/bootstrap.properties /config/bootstrap.properties
COPY GarageSaleRuntimeUtil/publish/jaxrsThirdPartyJars /opt/ibm/wlp/usr/shared/resources/jaxrsThirdPartyJars
COPY GarageSaleRuntimeUtil/publish/config/configDropins /config/configDropins/
COPY GarageSaleRuntimeUtil/publish/databaseDrivers/db2V9Drivers/db2jcc4.jar /opt/ibm/wlp/usr/shared/resources/db2drivers/db2jcc4.jar
COPY GarageSaleRuntimeUtil/publish/databaseDrivers/db2V9Drivers/db2jcc_license_cu.jar /opt/ibm/wlp/usr/shared/resources/db2drivers/db2jcc_license_cu.jar
COPY GarageSaleRuntimeUtil/publish/files/WASPersonaWebServicesHandlerFeature_1.0.0.201704030941.esa /gsResources/WASPersonaWebServicesHandlerFeature_1.0.0.201611170651.esa
#RUN installUtility install --acceptLicense WASPersonaWebServicesHandlerFeature --from=/gsResources/WASPersonaWebServicesHandlerFeature_1.0.0.201611170651.esa
RUN featureManager install /gsResources/WASPersonaWebServicesHandlerFeature_1.0.0.201611170651.esa --when-file-exists=replace --acceptLicense 
