apiVersion: v1
kind: Service
metadata:
  name: garagesale
  labels:
    name: garagesale
spec:
  selector:
    name: garagesale
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9080
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9043
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: garagesale
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: garagesale
    spec:
      containers:
      - name: garagesale
        image: garagesale-ee7:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
          - containerPort: 9043
        readinessProbe:
          httpGet:
            path: /
            port: 9080
        env:
        - name: MB_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-keystore-password
              key: password
        - name: MB_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-truststore-password
              key: password
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: garagesale
  labels:
    name: garagesale
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /GSjsf20LibertyWeb
        backend:
          serviceName: garagesale
          servicePort: 9043
      - path: /WASPersonaWebServicesPMIWeb
        backend:
          serviceName: garagesale
          servicePort: 9043          