kind: Secret
apiVersion: v1
metadata:
  name: db-credential
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  dbpw: ZGIyaW5zdDEK
type: Opaque
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged1'
subjects:
  - kind: ServiceAccount
    name: default
  - kind: ServiceAccount
    name: mysvcacct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged2'
subjects:
  - kind: ServiceAccount
    name: default
  - kind: ServiceAccount
    name: mysvcacct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged3'
subjects:
  - kind: ServiceAccount
    name: default
  - kind: ServiceAccount
    name: mysvcacct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
