kind: Deployment
apiVersion: apps/v1
metadata:
  name: gs-db2
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: gs-db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-db2
      deployment: gs-db2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gs-db2
        deployment: gs-db2
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: gs-db2
          env:
            - name: DB2INST1_PASSWORD
              value: db2passwd
            - name: LICENSE
              value: accept
            - name: APP
              value: gsale8
          securityContext:
            capabilities:
            privileged: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 50000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: libr-proxy1.fyre.ibm.com:5003/docker-registry-svt/v2/db2/svt-db2:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: mysvcacct
      serviceAccount: mysvcacct
      schedulerName: default-scheduler
