apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: db2-kustomize

resources:
- 00-role-n-sa.yaml
- 03-db2-secret.yaml
- 04-gs-db2-svc.yaml
- 04-gs-db2.yaml
- 04-ses-db2-svc.yaml
- 04-ses-db2.yaml

