apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
    name: garagesale-ee
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  applicationImage: hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/garagesale/garagesale-ee:ee10jdk17tol
  statefulSet: {}
  createKnativeService: false
  expose: true
  serviceability:
    size: 2Gi  
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9443
  route:
    termination: passthrough
  resources:
    limits:
      cpu: 256m
      memory: 600Mi
    requests:
      cpu: 128m
      memory: 400Mi
  probes:
    readiness:
      failureThreshold: 12
      httpGet:
        path: /health/ready
        port: 9080
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      failureThreshold: 12
      httpGet:
        path: /health/live
        port: 9080
      initialDelaySeconds: 15
      periodSeconds: 20
  env:
    - name: GSDB_SERVER_NAME
      value: 'gs-db2'
    - name: GSDB_NAME
      value: GSDB
    - name: GSDB_PORT
      value: "50000"
    - name: GSDB_USER
      value: db2inst1
    - name: GSDB_PASSWORD
      value: db2passwd
    - name: CCDB_SERVER_NAME
      value: 'gs-db2'
    - name: CCDB_NAME
      value: CCDB
    - name: CCDB_PORT
      value: "50000"
    - name: CCDB_USER
      value: db2inst1
    - name: CCDB_PASSWORD
      value: db2passwd
    - name: WSBANKDB_SERVER_NAME
      value: 'gs-db2'
    - name: WSBANKDB_NAME
      value: WSBANKDB
    - name: WSBANKDB_PORT
      value: "50000"
    - name: WSBANKDB_USER
      value: db2inst1
    - name: WSBANKDB_PASSWORD
      value: db2passwd
    - name: SESSIONDB_SERVER_NAME
      value: 'ses-db2'
    - name: SESSIONDB_NAME
      value: SESSIONS
    - name: SESSIONDB_PORT
      value: "50000"
    - name: SESSIONDB_USER
      value: db2inst1
    - name: SESSIONDB_PASSWORD
      value: db2passwd